language: python
python: 3.4
cache:
  directories:
    - $HOME/.pip-cache
env:
  - TOXENV=flake8
  - TOXENV=py26-py
  - TOXENV=py27-py
  - TOXENV=py33-py
  - TOXENV=py34-py
before_install:
  - pip install --download-cache $HOME/.pip-cache
  - pip install --download-cache $HOME/.pip-cache tox
script:
  - tox -v
